config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token

  def index
    @users = User.all
  end

  def create
    User.create!(email: params[:email])
    @users = User.all

    render json: { users: @users.to_json }
  rescue ActiveRecord::RecordInvalid => e
    render json: { error: e.message }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TestingRaceCondition</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<input id="email"/>
<button id="create_user" name="create_user" value="create_user">CREATE USER</button>
<button id='hacked_create_user' name='hacked_create_user' value='hacked_create_user'>HACKED CREATE USER</button>
<br>

<div id="users">
  <% @users.each do |user| %>
    <%= user.email %><br>
  <% end %>
</div>

<div id="error">
</div>

<script>
  let counter = 0;

  $('#create_user').on('click', () => {
    let email = $('#email').val();
    createUser(email);
  });

  $('#hacked_create_user').on('click', () => {
    let email = 'hacker_email_' + counter + '@example.com';
    for (let i = 0; i < 100; i ++) {
      createUser(email);
    }
    counter += 1;
  });

  function createUser(email) {
    $.post('<%= users_url %>', { email: email }).done(resp => {
      if (resp.users) {
        $('#users').html(JSON.parse(resp.users).map(user => user.email).join('<br>'));
        $('#email').val('');
      } else {
        $('#error').html(resp.error);
      }
    });
  }
</script>